services:
  db:
    image: postgres:17-bookworm
    pre_stop:
      - command: /bin/bash /backups/take-snapshot.sh
    container_name: postgres-db
    networks:
      - app-network
    volumes:
      - postgres_db:/var/lib/postgresql/data/
      - ./backups/scripts:/docker-entrypoint-initdb.d
      - ./backups/data:/backups
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  identity-web:
    build: .
    image: ghcr.io/uklibraries/identity_service:latest
    networks:
      - app-network
    container_name: identity-web
    expose:
      - 8000
    volumes:
      - identity:/app
      - static:/app/staticfiles
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path : ./pyproject.toml
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./.env

  frontend-proxy:
    image: nginx:1.29
    networks:
      - app-network
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/static:ro
    depends_on:
      - identity-web

volumes:
  identity:
  postgres_db:
  static:

networks:
  app-network:
    driver: bridge
